name: Test Workflow

on:
    push:
        branches:
            - main

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Create Folder
              run: mkdir folder1

            - name: list folders
              run: ls -l

            - name: Create File
              run: touch file1.txt
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        steps:
            - name: list folders
              run: ls -l

    job-3:
        runs-on: ubuntu-latest
        needs: job-2
        steps:
            - name: Create Folder
              run: mkdir folder1

            - name: list folders
              run: ls -l

            - name: Create File
              run: touch file1.txt