name: Test Workflow

on:
    push:
        branches:
            - main
    

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
          - name: clone repo to runner
            uses: actions/checkout@v4
          
          - name: build Image
            run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/basic-nodejs-s3 .

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
            
          - name: Push Image to Docker Hub
            run: docker push ${{ vars.DOCKERHUB_USERNAME }}/basic-nodejs-s3
    
    Test-job:
      runs-on: ubuntu-latest
      steps:
        - name: pull image from Docker Hub
          run: docker pull ${{ vars.DOCKERHUB_USERNAME}}/basic-nodejs-s3