name: Test Workflow

on:
    push:
        branches:
            - main

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Create Folder
              run: mkdir folder1

            - name: list folders
              run: ls -l

            - name: Create File
              run: touch file1.txt

            - name: Echo to File
              run: echo "Hello, World!" > file1.txt

            - name: list folders
              run: ls -l