name: Test Workflow

on:
    push:
        branches:
            - main
    
env:
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
          - name: clone repo to runner
            uses: actions/checkout@v4

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          - name: build Image
            run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/basic-nodejs-s3:${{ env.BUILD_NUMBER }} .
            
          - name: Push Image to Docker Hub
            run: docker push ${{ vars.DOCKERHUB_USERNAME }}/basic-nodejs-s3:${{ env.BUILD_NUMBER }}

          - name: Tag Image to Latest
            run: docker tag ${{ vars.DOCKERHUB_USERNAME }}/basic-nodejs-s3:${{ env.BUILD_NUMBER }} ${{ vars.DOCKERHUB_USERNAME }}/basic-nodejs-s3:latest
    
    Test-job:
      runs-on: ubuntu-latest
      needs: ["build-and-push"]
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: pull image from Docker Hub
          run: docker pull ${{ vars.DOCKERHUB_USERNAME}}/basic-nodejs-s3

        - name: Run Tests
          run: docker run ${{ vars.DOCKERHUB_USERNAME}}/basic-nodejs-s3:latest npm test