name: Test Workflow

on:
    push:
        branches:
            - main
    

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
          - name: list folder
            run: ls -l

          - name: clone repo to runner
            uses: actions/checkout@v4
          
          - name: list folder
            run: ls -l